[package]
name = "xdevs"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.8"
xdevs-no-std-macros = { path = "macros", version = "0.1.0" }

[features]
std = []
